#########################################################################
#数据源配置
#########################################################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssh?useSSL=false
    username: root
    password: root
    tomcat:
      max-active: 100
      max-idle: 200
      initial-size: 20
#jpa设置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
#模板thymeleaf设置 
  thymeleaf:
    cache: false
#MVC设置
  mvc:
    view:
      prefix: /
      suffix: .html
#配置I18N资源文件，供thymeleaf读取
  messages:
    basename: static/i18n/messages
    cache-duration: 3600
    encoding: UTF-8
#配置邮箱服务
  mail: 
    host: smtp.163.com
    username: hdbjlizhe@163.com
    password: hdlizhe850318
    port: 465
    protocol: smtp
    test-connection: true 
    properties:
      mail: 
        debug: true
        host: smtp.163.com
        transport: 
          protocol: smtp
        smtp: 
          auth: true
          port: 465
          timeout: 600000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          starttls: 
            enable: true
            required: true
#########################################################################    
#日志级别：TRACE < DEBUG < INFO < WARN < ERROR < FATAL。
#########################################################################
logging:
  config: classpath:logback-spring.xml
#########################################################################    
#自定义参数
#########################################################################
message:
  welcome: 欢迎
mail: 
  from: 
    addr: hdbjlizhe@163.com   #邮件发送地址
#########################################################################
#产业招商精准招商FTP资料库
#########################################################################
ftpServer:
  host: 10.151.248.185
  port: 21
  userName: chanyechu
  password: chanyechu
